<a href="https://colab.research.google.com/github/PKpacheco/linear-algebra-for-machine-learning/blob/main/01_data_standardization_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for Machine Learning

This notebook explores how linear algebra concepts can be applied to equipment condition data.

The dataset contains measurements for voltage, current, and temperature. Each observation is classified as either `normal` or `failed`.

The project covers:

* Data inspection
* Mean and standard deviation
* Feature standardization
* Vectors and vector magnitude
* Dot products
* Linear classification
* Loss functions and accuracy

In [10]:
# import

# Pandas is used to load and manipulate tabular data.
import pandas as pd

# NumPy provides mathematical operations for vectors and matrices.
import numpy as np

# Plotly can be used to create interactive data visualizations.
import plotly.express as px

Understanding the Dataset

Before performing mathematical calculations, it is important to inspect the structure and quality of the data.

The dataset contains:

condition: the known equipment condition
voltage: the measured voltage
current: the measured electrical current
temperature: the measured temperature

In [11]:
#loading dataset
DATA_URL = (
    "https://raw.githubusercontent.com/PKpacheco/linear-algebra-for-machine-learning/refs/heads/main/data_algebra.csv"
)

csv_data = pd.read_csv(DATA_URL)
csv_data.head()

  condition    voltage     current  temperature
0    normal  13.036111  458.460370     6.879090
1    normal  11.135509  458.156781     6.394905
2    normal  10.296578  459.431151     2.736525
3    normal  10.553064  457.141002     5.624983
4    normal   9.880487  460.601899     1.843793

The dataset contains 10 observations and 4 columns.

The `condition` column contains text labels, while voltage, current, and temperature are numerical features.

All columns contain 10 non-null values, which means there are no missing values in this dataset.

In [6]:
#info data
csv_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   condition    10 non-null     object
 1   voltage      10 non-null     float64
 2   current      10 non-null     float64
 3   temperature  10 non-null     float64
dtypes: float64(3), object(1)
memory usage: 452.0+ bytes

In [13]:
# Return the number of rows and columns in the dataset.
rows, columns = csv_data.shape

print("Number of observations:", rows)
print("Number of columns:", columns)

Number of observations: 10
Number of columns: 4

In [15]:
# Count missing values in each column.
csv_data.isna().sum()

condition      0
voltage        0
current        0
temperature    0
dtype: int64

In [7]:
#calculate mean

mean_voltage = csv_data['voltage'].mean().round(2)
mean_current = csv_data['current'].mean().round(2)
mean_temperature = csv_data['temperature'].mean().round(2)

print('>>> mean_voltage = ', mean_voltage)
print('>>> mean_current = ', mean_current)
print('>>> mean_temperature =',mean_temperature)

>>> mean_voltage =  19.31
>>> mean_current =  2530.08
>>> mean_temperature = 28.38

In [16]:
# Calculate the standard deviation of each numerical feature.
std_voltage = round(csv_data["voltage"].std(), 2)
std_current = round(csv_data["current"].std(), 2)
std_temperature = round(csv_data["temperature"].std(), 2)

print("Standard deviation - voltage:", std_voltage)
print("Standard deviation - current:", std_current)
print("Standard deviation - temperature:", std_temperature)

print('>>> std_voltage =', std_voltage)
print('>>> std_current =', std_current)
print('>>> std_temperature =',std_temperature)

Standard deviation - voltage: 9.24
Standard deviation - current: 2183.37
Standard deviation - temperature: 25.16
>>> std_voltage = 9.24
>>> std_current = 2183.37
>>> std_temperature = 25.16

In [17]:
#standardized voltage

csv_data['standardized_voltage'] = ((csv_data['voltage'] - mean_voltage )/ std_voltage).round(2)
csv_data.head()

  condition    voltage     current  temperature  standardized_voltage
0    normal  13.036111  458.460370     6.879090                 -0.68
1    normal  11.135509  458.156781     6.394905                 -0.88
2    normal  10.296578  459.431151     2.736525                 -0.98
3    normal  10.553064  457.141002     5.624983                 -0.95
4    normal   9.880487  460.601899     1.843793                 -1.02

In [18]:
#standardized current
csv_data['standardized_current'] = ((csv_data['current'] - mean_current )/ std_current).round(2)
csv_data.head()

,condition,voltage,current,temperature,standardized_voltage,standardized_current
0,normal,13.036111,458.460370,6.879090,-0.68,-0.95
1,normal,11.135509,458.156781,6.394905,-0.88,-0.95
2,normal,10.296578,459.431151,2.736525,-0.98,-0.95
3,normal,10.553064,457.141002,5.624983,-0.95,-0.95
4,normal,9.880487,460.601899,1.843793,-1.02,-0.95

In [19]:
#standardized temperature
csv_data['standardized_temperature'] = ((csv_data['temperature'] - mean_temperature )/ std_temperature).round(2)
csv_data.head()

,condition,voltage,current,temperature,standardized_voltage,standardized_current,standardized_temperature
0,normal,13.036111,458.460370,6.879090,-0.68,-0.95,-0.85
1,normal,11.135509,458.156781,6.394905,-0.88,-0.95,-0.87
2,normal,10.296578,459.431151,2.736525,-0.98,-0.95,-1.02
3,normal,10.553064,457.141002,5.624983,-0.95,-0.95,-0.90
4,normal,9.880487,460.601899,1.843793,-1.02,-0.95,-1.05